language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angularjs-silex' ]; then cd .. && eval "mv $currentfolder generator-angularjs-silex" && cd generator-angularjs-silex; fi

